[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Python solutions, likely suboptimal"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "numpy==2.1.3",
    "scipy==1.14.1",
    "tqdm>=4.67.1",
]
